blueprints/images.py
import os
from datetime import datetime
from PIL import Image as PILImage
import random
import secrets
import time
import imagehash


from flask import request, send_from_directory, render_template, redirect, url_for, jsonify, \
    Blueprint, current_app

from database import *
from utils import process_embed


app = Blueprint('images', __name__)


### IMAGES AND STUFF

@app.route("/i/<id>", methods=['GET', 'DELETE'])
def get_img(id):
    if id.endswith('\u200B'):
        invisibleurl: InvisibleUrl = InvisibleUrl.query.filter_by(url=id).first_or_404(
            description='Invalid invisible URL')

        id = invisibleurl.imgid

        return redirect(url_for("images.get_img", id=id))

    if request.method == 'DELETE':
        return redirect(url_for('dashboard.delete_image', id=id))

    image: Image = Image.query.filter_by(id=id).first_or_404(description='Image not found')
    user: User = User.query.filter_by(uid=image.user).first()
    embed: Embed = Embed.query.filter_by(user=image.user).first()

    if embed is None:
        embed = Embed(user=user.uid, color="", title="", desc="", author_name="", author_url="", provider_name="", provider_url="")

    embed = process_embed(embed, image, user)
    embed_adv = embed.author_name != "" or embed.author_url != "" or embed.provider_name != "" or embed.provider_url != ""

    color_on = embed.color != ""
    title_on = embed.title != ""
    desc_on = embed.desc != ""

    return render_template(
        "image.html",
        img_name=image.name,
        img_id=image.id,
        img_ext=image.ext,
        size_kb=str(round(image.size_b / 1024, 2)),
        size_mb=str(round(image.size_b / (1024 * 1024), 2)),
        uploaded_by=user.username,
        uploaded_uid=user.uid,
        uploaded_at=datetime.utcfromtimestamp(
            image.upload_time
        ).strftime("%d.%m.%Y %H:%M"),
        embed_color=embed.color,
        embed_title=embed.title,
        embed_desc=embed.desc,
        embed_adv=embed_adv,
        embed_color_on=color_on,
        embed_title_on=title_on,
        embed_desc_on=desc_on,
    )


@app.route("/<id>")
def root_img(id):
    return redirect(url_for("images.get_img", id=id))


@app.route("/i/raw/<id>")
def img_raw(id):
    img: Image = Image.query.filter_by(id=id).first_or_404(description='Image not found')
    usr = img.user
    dir = os.path.join(current_app.config['SHARX_CONFIG']['storage_folder'], str(usr))
    filename = img.id + img.ext

    return send_from_directory(dir, filename)


@app.route("/i/embed/<id>")
def get_embed(id):
    image: Image = Image.query.filter_by(id=id).first_or_404(description='Image not found')
    user: User = User.query.filter_by(uid=image.user).first()
    embed: Embed = Embed.query.filter_by(user=image.user).first()

    if embed is None:
        embed = Embed(user=user.uid, color="", title="", desc="", author_name="", author_url="", provider_name="", provider_url="")

    embed = process_embed(embed, image, user)

    em_json = {
        'type': 'link',
        'version': '1.0'
    }
    if embed.author_name != "":
        em_json['author_name'] = embed.author_name
    if embed.author_url != "":
        em_json['author_url'] = embed.author_url
    if embed.provider_name != "":
        em_json['provider_name'] = embed.provider_name
    if embed.provider_url != "":
        em_json['provider_url'] = embed.provider_url

    return jsonify(em_json)

@app.route("/upload", methods=['POST', 'GET'])
def upload():
    if request.method == 'GET':
        return render_template("405.html"), 405
    attributes = request.form.to_dict(flat=False)
    if 'uid' not in list(attributes.keys()) or 'key' not in list(attributes.keys()):
        return "Required value not in request attributes", 400
    elif 'image' not in list(request.files.to_dict(flat=False).keys()):
        return "'image' not provided", 400

    user: User = User.query.filter_by(uid=attributes['uid'][0]).first()

    if user is None:
        return "User not found", 401

    if attributes['key'][0] != user.key:
        return "Wrong upload key", 401
    file = request.files['image']
    name, ext = os.path.splitext(file.filename)
    # filename = file.filename
    file.flush()
    size = os.fstat(file.fileno()).st_size
    if ext not in current_app.config['SHARX_CONFIG']['allowed_extensions']:
        return "Unsupported file type", 415
    elif size > 6000000:
        return 'File size too large', 400

    image = PILImage.open(file)
    data = list(image.getdata())
    file_without_exif = PILImage.new(image.mode, image.size)
    file_without_exif.putdata(data)

    avhash = str(imagehash.average_hash(file_without_exif))

    imghash: ImgHash = ImgHash.query.filter_by(hash=avhash, user=int(attributes['uid'][0])).first()
    if imghash is not None:
        ex_image: Image = Image.query.filter_by(id=imghash.imgid).first()
        if user.invisibleurls != 1:
            return jsonify({"url": url_for("images.get_img", id=ex_image.id, _external=True),
                            "raw": url_for("images.img_raw", id=ex_image.id, _external=True)})


        iurl: InvisibleUrl = InvisibleUrl.query.filter_by(imgid=ex_image.id).first()
        if iurl is None:
            ok = False
            while not ok:
                charset = ['\u200B', '\u2060', '\u180E', '\u200D', '\u200C']
                invisible_id = [random.choice(charset) for _ in range(24)]
                invisible_id.append('\u200B')
                invisible_id = ''.join(invisible_id)
                existing: InvisibleUrl = InvisibleUrl.query.filter_by(url=invisible_id).first()
                ok = existing is None

            iurl: InvisibleUrl = InvisibleUrl(url=invisible_id, imgid=ex_image.id)
            db.session.add(iurl)
            db.session.commit()

        return jsonify({"url": url_for("images.root_img", id="", _external=True) + iurl.url,
                        "raw": url_for("images.img_raw", id=ex_image.id, _external=True)})
                        

    img_id = secrets.token_urlsafe(5)
    imghash = ImgHash(hash=avhash, imgid=img_id, user=int(attributes['uid'][0]))
    db.session.add(imghash)
    filename = img_id + ext
    if not os.path.exists(os.path.join(current_app.config['SHARX_CONFIG']['storage_folder'], str(user.uid))):
        os.mkdir(os.path.join(current_app.config['SHARX_CONFIG']['storage_folder'], str(user.uid)))
    file_without_exif.save(os.path.join(
        current_app.config['SHARX_CONFIG']['storage_folder'], str(user.uid), filename))
    user.storage_used += size
    img: Image = Image(id=img_id, name=name, ext=ext, upload_time=round(time.time()), size_b=size,
                       user=attributes['uid'][0])
    db.session.add(img)
    db.session.commit()
    if user.invisibleurls == 1:
        ok = False
        while not ok:
            charset = ['\u200B', '\u2060', '\u180E', '\u200D', '\u200C']
            invisible_id = [random.choice(charset) for _ in range(24)]
            invisible_id.append('\u200B')
            invisible_id = ''.join(invisible_id)
            existing: InvisibleUrl = InvisibleUrl.query.filter_by(url=invisible_id).first()
            ok = existing is None

        url: InvisibleUrl = InvisibleUrl(url=invisible_id, imgid=img_id)
        db.session.add(url)
        db.session.commit()
        return jsonify({"url": url_for("images.root_img", id="", _external=True) + invisible_id,
                        "raw": url_for("images.img_raw", id=img_id, _external=True)})

    return jsonify({"url": url_for("images.get_img", id=img_id, _external=True),
                    "raw": url_for("images.img_raw", id=img_id, _external=True)})

blueprints/links.py
from flask import send_from_directory, render_template, redirect, Blueprint, current_app

from database import *

app = Blueprint('links', __name__)


### LINKS

@app.route("/discord/")
def discord():
    return redirect(f"https://discord.gg/{current_app.config['SHARX_CONFIG']['discord']}", code=301)


@app.route("/favicon.ico")
def favicon():
    return send_from_directory("config", "favicon.ico")


@app.route("/logo.png")
def logo():
    return send_from_directory("config", "logo.png")


@app.route("/")
def home():
    img_count = len(Image.query.all())
    usr_count = len(User.query.all())
    users = User.query.all()
    total_storage = round(sum(user.storage_used
                              for user in users) / (1024 * 1024), 2)
    return render_template("index.html",
                           user_count=usr_count,
                           storage_used=total_storage, image_count=img_count)


@app.route('/repo')
def repo():
    # try:
    #     link = subprocess.check_output(["git", "remote", "get-url", 'origin']).strip().decode()
    #     if link.startswith('git@') or link.startswith('git://') or link.startswith('ssh://'):
    #         link = link.replace('git@', '').replace(':', '/').replace('.git', '')
    # except Exception:
    #     link = "https://gitlab.com/GGORG/SharX"
    link = "https://gitlab.com/GGORG/SharX"

    return redirect(link, code=301)

templates/405.html
<!--405 Method not allowed-->
<!--You can't use the {{ request.method }} method!-->

{% extends "header.html" %}

{% block body %}

<h1>405 Method not allowed</h1>
<h2>You can't use the {{ request.method }} method!</h2>

{% endblock %}

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="mb-3">
    {% if field.type == "BooleanField" %}
    <div class="form-check form-switch">
        {{ field(class_="form-check-input") }}
        {{ field.label(class_="form-check-label") }}
        {% else %}
        <dt>{{ field.label(class_="form-label") }}
        <dd>{{ field(class_="form-control") }}
            {% endif %}
            {% if field.errors %}
            <ul class=errors>
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </dd>
    </div>
    {% endmacro %}

templates/account.html
{% extends "dashboard_header.html" %}

{% block main %}

<h1>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }} - Dashboard (Account)</h1>
<h2>Welcome, <strong>{{ username }}</strong>!</h2>
<h3>Here is your account information:</h3>

<div aria-hidden="true" class="modal fade" id="regenerateKeyModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Regenerate key</h5>
                <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to regenerate your upload key?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">No</button>
                <a class="btn btn-primary" href="{{ url_for('dashboard.regenerate_key') }}"
                   style="background-color: var(--bs-red);">Yes</a>
            </div>
        </div>
    </div>
</div>

<br>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">Email</h5>
                            <p class="card-text"><strong>{{ email }}</strong></p>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-envelope fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">UID</h5>
                            <p class="card-text"><strong>{{ uid }}</strong></p>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">Upload key</h5>
                            <p class="card-text spoiler">{{ key }}</p>
                            <a class="btn btn-primary" data-bs-target="#regenerateKeyModal" data-bs-toggle="modal" href="#">Regenerate</a>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-key fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">Password</h5>
                            <a class="btn btn-primary" href="{{ url_for('dashboard.change_password') }}">Change it</a>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-unlock-alt fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<br>

<div class="card border-left-primary shadow py-2" style="width: 22rem;">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col">
                <h5 class="card-title" style="color: var(--bs-red)">Delete account</h5>
                <a class="btn btn-primary" data-bs-target="#deleteAccountModal" data-bs-toggle="modal" href="#" style="background-color: var(--bs-red)">Delete your
                    account</a>
            </div>
            <div class="col-2">
                <i class="fas fa-user-slash fa-2x text-gray-300" style="color: var(--bs-red)"></i>
            </div>
        </div>
    </div>
</div>

<div aria-hidden="true" class="modal fade" id="deleteAccountModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete account</h5>
                <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete your account and all uploaded images?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal" type="button">No</button>
                <a class="btn btn-primary" href="{{ url_for('dashboard.delete_account') }}"
                   style="background-color: var(--bs-red)">Yes</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/change_password.html
{% extends "dashboard_header.html" %}

{% block main %}

<h1>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }} - Dashboard (Change password)</h1>
<h2>Welcome, <strong>{{ username }}</strong>!</h2>
<h3>Here you can change your password</h3>
{% from "_formhelpers.html" import render_field %}
<form action="{{ url_for('dashboard.change_password') }}" method=post>
    <dl>
        {{ render_field(form.old_password) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm) }}
    </dl>
    <p><input type=submit value="Change password"></p>
</form>

{% endblock %}

templates/dashboard.html
{% extends "dashboard_header.html" %}

{% block main %}

<h1>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }} - Dashboard</h1>
<h2>Welcome, <strong>{{ username }}</strong>!</h2>
<h3>Thanks for using {{ config['SHARX_HOST_NAME'] }}!</h3>



<br>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">Image count</h5>
                            <p class="card-text">You have uploaded <strong>{{ img_count }}</strong>
                                image{{ '' if img_count == 1 else 's' }}!</p>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-images fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">UID</h5>
                            <p class="card-text">Your user ID is <strong>{{ uid }}</strong>.</p>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">Invites</h5>
                            <p class="card-text">You have <strong>{{ inv_count }}</strong> invite{{ '' if inv_count == 1 else 's' }}! {% if inv_count == 0 %}<i class="fas fa-sad-tear" style="color: var(--bs-yellow)"></i>{% endif %}</p>
                            {% if inv_count > 0 %}
                            <a class="btn btn-primary" data-bs-target="#invitesModal" data-bs-toggle="modal" href="#">View</a>
                            {% endif %}
                        </div>
                        <div class="col-2">
                            <i class="fas fa-link fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card border-left-primary shadow py-2" style="width: 22rem;">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            <h5 class="card-title">Storage</h5>
                            <p class="card-text">You have used <strong>{{ space }} MB</strong> of storage!</p>
                        </div>
                        <div class="col-2">
                            <i class="fas fa-hdd fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<br>

<div class="card border-left-primary shadow py-2" style="width: 22rem;">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col">
                <h5 class="card-title">MOTD</h5>
                <p class="card-text">{{ config['SHARX_HOST_MOTD'] }}</p>
            </div>
            <div class="col-2">
                <i class="fas fa-comment fa-2x text-gray-300"></i>
            </div>
        </div>
    </div>
</div>

<div aria-hidden="true" class="modal fade" id="invitesModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Invites</h5>
                <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                    {% for inv in invites %}
                    <li class="list-group-item"><div class="spoiler">{{ inv.code }}</div></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/embed_conf.html
{% extends "dashboard_header.html" %}

{% block main %}

<h1>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }} - Dashboard (Embed configuration)</h1>
<h2>Welcome, <strong>{{ username }}</strong>!</h2>
<h3>Here you can configure your embeds</h3>
<div class="container">
    <div class="row align-items-start">
        <div class="col">
            <h4>Tip: You can leave some of them blank!</h4>
            {% from "_formhelpers.html" import render_field %}
            <form action="{{ url_for('dashboard.embed_conf') }}" method=post>
                <dl>
                    {{ render_field(form.color) }}
                    {{ render_field(form.title) }}
                    {{ render_field(form.desc) }}
                    {{ render_field(form.author_name) }}
                    {{ render_field(form.author_url) }}
                    {{ render_field(form.provider_name) }}
                    {{ render_field(form.provider_url) }}
                </dl>
                <p><input type=submit value="Apply"></p>
            </form>
        </div>
        <div class="col">
            <p>
                The available variables are:
                <br>
                {% for name in vars %}
                <code>{{ name }}</code>

                {% endfor %}
            </p>

            <br>
            <br>
            
            <!-- <img src="/static/embed.png" alt="Embed screenshot"> -->
        </div>
    </div>
</div>

{% endblock %}

templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="{{ config['SHARX_HOST_NAME'] }}" property="og:title">
    <meta content="{{ config['SHARX_HOST_MOTD'] }}" property="og:description">
    <meta content="#ff6600" name="theme-color">
    <meta content="dark" name="color-scheme">
    <title>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }} - {% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.0.2/dist/css/bootstrap-night.min.css" rel="stylesheet"
        crossorigin="anonymous">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous"> -->
    <link href="/static/style.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2cff27eaca.js" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <img src="/logo.png" alt="" width="30" class="d-inline-block align-text-top me-2">
            <a class="navbar-brand" href="{{ url_for('links.home') }}">{{ config['SHARX_HOST_NAME'] }}</a>
            <button class="navbar-toggler" data-bs-target="#headerNavBar" data-bs-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="headerNavBar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('links.home') }}"><i class="fas fa-home"></i>
                            Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('links.discord') }}"><i class="fab fa-discord"></i>
                            Discord</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('dashboard.dashboard') }}"><i
                                class="fas fa-tachometer-alt"></i> Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('links.repo') }}"><i class="fab fa-git-alt"></i>
                            Source Code</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category if category != 'message' else 'info' }} alert-dismissible fade show" role="alert">
            {% if category == 'danger' %}
            <i class="fas fa-exclamation-triangle" style="color: var(--bs-red)"></i>
            {% elif category == 'warning' %}
            <i class="fas fa-exclamation-triangle" style="color: var(--bs-yellow)"></i>
            {% elif category == 'info' %}
            <i class="fas fa-info-circle" style="color: var(--bs-aqua)"></i>
            {% elif category == 'success' %}
            <i class="fas fa-check-circle" style="color: var(--bs-green)"></i>
            {% endif %}

            {{ message }}
            <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block body %}{% endblock %}
    </div>

    <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/script.js"></script>
</body>

</html>

templates/image.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="dark" name="color-scheme">
    <meta content="summary_large_image" name="twitter:card">
    <meta content="{{ url_for('images.img_raw', id=img_id) }}" name="twitter:image">
    <meta content="{{ url_for('images.img_raw', id=img_id) }}" name="twitter:image:src">
    <meta content="{{ url_for('images.img_raw', id=img_id) }}" property="og:image">
    {% if embed_color_on %}
    <meta content="{{ embed_color }}" name="theme-color">
    {% endif %}
    {% if embed_title_on %}
    <meta content="{{ embed_title }}" property="og:title">
    <meta content="{{ embed_title }}" name="twitter:title">
    {% endif %}
    {% if embed_desc_on %}
    <meta content="{{ embed_desc }}" name="twitter:description">
    <meta content="{{ embed_desc }}" property="og:description">
    {% endif %}
    {% if embed_adv %}
    <link href="{{ url_for('images.get_embed', id=img_id, _external=True) }}" type="application/json+oembed">
    {% endif %}
    <title>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }} | {{ img_name }}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.0.2/dist/css/bootstrap-night.min.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: var(--bs-gray);">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('links.home') }}">{{ config['SHARX_HOST_NAME'] }}</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('links.home') }}">home</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container mt-4">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="d-flex justify-content-center align-items-center">
        <div class="card text-center">
            <img alt="Image" class="card-img-top" src="{{ url_for('images.img_raw', id=img_id) }}">
            <hr class="dropdown-divider">
            <div class="card-body">
                <h1 class="card-title">{{ img_name + img_ext }}</h1>
                <p class="card-text" style="font-size: 1.5rem;">
                    <strong>ID:</strong> {{ img_id }}
                    <br>
                    <strong>Size:</strong> {{ size_kb }} KB ({{ size_mb }} MB)
                    <br>
                    <strong>Uploaded by:</strong> {{ uploaded_by }} (UID {{ uploaded_uid }})
                    <br>
                    <strong>Uploaded at:</strong> {{ uploaded_at }} UTC
                </p>
                <a class="btn btn-primary" href="{{ url_for('images.img_raw', id=img_id) }}">View raw</a>
            </div>
        </div>
    </div>
</div>

<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js">
</script>
</body>

</html>

templates/index.html
{% extends "header.html" %}

{% block body %}

<h1>{{ config['SHARX_HOST_NAME'] }} v{{ config['SHARX_HOST_VERSION'] }}</h1>
<h2>ShareX image hosting</h2>
<br>
<br>
<h2>MOTD</h2>
<h3>{{ config['SHARX_HOST_MOTD'] }}</h3>
<br>
<br>
<h2>Statistics:</h2>
<ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Users:</strong> {{ user_count }}</li>
    <li class="list-group-item"><strong>Storage used:</strong> {{ storage_used }} MB</li>
    <li class="list-group-item"><strong>Images uploaded:</strong> {{ image_count }}</li>
</ul>

{% endblock %}